on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: test-actions

jobs:
  test-app:
    runs-on: ${{ matrix.config.os }}

    name: Test app ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: release}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: |
            shinytest2-testing
          extra-packages: |
            local::.

      # ## Suggested usage
      # - name: Test app
      #   uses: rstudio/shinytest2/actions/test-app@actions/v1
      #   with:
      #     app-dir: |
      #       tests/testthat/apps/hello

      - name: Test app (main)
        uses: rstudio/shinytest2/actions/test-app@actions/v1
        with:
          app-dir: "tests/testthat/apps/window"

      - name: Test app (PR)
        if: github.event_name == 'pull_request'
        uses: ./actions/test-app
        with:
          app-dir: |
            tests/testthat/apps/text_html,tests/testthat/apps/window,
            tests/testthat/apps/text_html
            tests/testthat/apps/text_html
